### PR TITLE
Improved access file actions interaction

### PR DESCRIPTION
**Pull request by beckyconning**
ezgif com-video-to-gif

### CODE REVIEW

**Comment by garyb** [comment]
You think that's better than the controls appearing with `:hover`?

**Comment by beckyconning** [comment]
I do but I'm open to alternate opinions. This is more consistent across screenreader, touchscreen and mouse based interfaces.

Alternatively there could be some visual element that presents these actions when clicked or the actions could always be visible.

**Comment by garyb** [comment]
It is more consistent, but it seems like a totally unnatural behaviour for a mouse in a browser-based interface - I would never think to select something in this way to get the context sensitive menu. The `title` should help with that, but it still seems like an odd choice to me - the golden rule of UX is the principle of least surprise.

I'm not sure I understand why it's a problem for the mouse based interface to differ from the other two? There's a more serious problem for screen readers, which is that the items in the list can't even be tabbed to. If that did actually work this wouldn't really be a problem, as screen readers do activate states like `:hover`, so when running through the list the options would actually be present.

I think generally SlamData will always be a very problematic experience for screen readers, as it's a _visual_ analytics app we're making here, not a website. How do you read a graph out, or sensibly read a huge table of information? To be blunt, I think it's actually impossible to provide a good experience throughout, and it will only get worse as we move to the card interface.

**Comment by garyb** [comment]
Actually though, there is a change we could make here that I would find acceptable: removing the "open on title click" action, and instead having that as an action just like the rest that are presented. If the items behaved the same wherever you clicked them, my problems with the interaction would go away.

**Comment by beckyconning** [comment]
I don't think it will be hard to provide a good experience for screenreader users in SlamData but I appreciate your concerns.

Is your suggestion to have clicking the file name selects the file and to open the file there is another option on the right that opens the file?

**Comment by garyb** [comment]
I think it's something we (as in the team) should probably discuss, as we could burn a tremendous amount of time trying to make everything screen-readable and end up with an experience that is still unusable in reality.

Yep! Clicking _anywhere_ on the item should do the same thing: present a list of options of what to do next with that item.

**Comment by beckyconning** [comment]
I really don't think its hard. We just need to provide a descriptive alternative wherever its easy to do so. Tables have pages, screenreaders allow you to skip over sections such as tables and most screenreader users have their speed set incredibly high. It would be nice if we could include this sort of thing in the grammar of graphics type stuff but if thats too much work then supporting the general user interface and making it clear when things aren't available will still bring a lot of value to screenreader users as well as making the application far easier to test.

**Comment by beckyconning** [comment]
I'm totally happy with that suggestion btw : ).

**Comment by beckyconning** [comment]
ezgif com-video-to-gif-3

**Comment by beckyconning** [comment]
ezgif com-video-to-gif-4

**Comment by garyb** [comment]
@becky maybe we should even remove the underline behaviour for the items on rollover, as it still implies linkiness? And use the darker text/icon state for the hover of the whole item, not just the item title.

@jdegoes what do you think of this approach?

**Comment by beckyconning** [comment]
I agree with your suggestions re underline behaviour and hover state.

If the end result is that we leave the hover behaviour in thats okay for now too. The main thing I need is that aria-label on whatever the thing you click to select the item is.

**Comment by garyb** [comment]
Well hopefully we can get a consensus that something like this is the way to go. It seems more in line with the direction we're moving for the card interface too: take thing, present next-steps options.

Plus you can still double click to open stuff in the listing here, although that's almost entirely undiscoverable and again a bit weird for a web interface.

The only thing I have a concern about is whether the "click item, then open" situation may be a bit tedious when you're traversing through a deep folder structure. I don't know how often that happens in a real world nosql database though.

**Comment by jdegoes** [comment]
I'm not a fan of making the experience the same across all devices. In particular, showing the options on hover makes the actions trivially _discoverable_ to a desktop user. A mobile user doesn't have this benefit, which is unfortunate, but doesn't matter since the interface will be changing anyway.

I would also consider that moving from a single-click, to forcing the user to open the toolbar, and then select an icon, makes the interface harder to use. By far the most common activity is opening a file, so it makes sense to design an interaction semantic that's obvious (underline, linked text) and separate from the other, far less common interaction semantics (download, etc.).

As for the other bits:

1. SlamData is most definitely a *data visualization* application. The cost of providing full accessibility to blind and visually impaired people is too much for our company to bare (we could pay that cost and not see a single user!). So while we can avoid designs that are overtly hostile, and pay small prices here for things that have *dual benefits* to testing and screen readers, we cannot design the application for individuals who are visually impaired. That would be like designing Photoshop for the visually impaired: most likely such an application would be forced to target _only_ visually impaired individuals because it would be so radically different than one targeting individuals with normal eyesight. That is not our business and we cannot pay its costs (except as noted above).
2. Using the structure viewer to explore the file system in a totally card-centric user-interface will enable us to have good and consistent interaction semantics across mobile and desktop, and will remove the utility of the hover menus that now appear. Note in that interface, a single click or tap is all that's necessary to "open" a file / notebook, so it satisfies my concern above about making the dominant choice different and substantially easier than niche choices (niche choices will move to the card backside).
3. Given (2), I'm not particularly keen to make radical changes or any significant investments in the existing interface. We need to be working on 3.x, not tweaking 2.x! :smile: Small things that help testing are fine, but we could spend a few months polishing 2.x and be no closer to 3.x, and a lot of that work would be throwaway. Better to focus our efforts on fixing the core usability problems at the heart of the 2.x interface line (no one ever complains about the file system component, FWIW).

**Comment by beckyconning** [comment]
Cool, @garyb are you okay with me adding the aria-label to the thing you click to select the file and leaving everything else as it was?

**Comment by garyb** [comment]
I'd go ahead and do it myself, but I'm not sure exactly which element needs it, so please do :)

After that I'll address the other couple of indentation foilbles etc. in the other PR and ask you to re-review.

**Comment by beckyconning** [comment]
Thanks @garyb

**Comment by beckyconning** [comment]
This isn't quite right, just fixing a couple of things.

**Comment by beckyconning** [comment]
Sorry for the delay, I've been doing more feature test stuff and reading the hello.js docs.

I won't do it now but I realised what I actually want which is to have a select mode which allows you to select multiple files and perform an action on from a list of actions. This is essentially what the card based discover interface will allow so 🎉.

The interactions are now the same as before* but we're using the DOM as the present / don't present model and there is an aria label for selecting / unselecting a file.

* The one thing I have changed from the original interactions is removing the double click interaction. Is this okay? It felt funny to me and you mentioned it too but if we'd rather save the fuss I'll add it straight back in now.

**Comment by garyb** [comment]
I have no problem at all getting rid of double-click. @jdegoes?

**Comment by jdegoes** [comment]
👍

**Comment by garyb** [comment]
Sorry to drag this out, but what's the advantage of changing the state "manually" based on mouse events, rather than relying on `:hover`? I would have thought `:hover` is better for usability, since keyboard focus also triggers it.

**Comment by beckyconning** [comment]
Support for `aria-hidden` is not as high as support for reporting of dom removals and additions. 

Most tools don't allow keyboard focus of `div`s although if we changed the file name and actions container to a link that would potentially fix that (i'm not sure how nested 'a's work in terms of accessibility).

In general I prefer to stick to presenting as much of the DOM as possible. Although thats not a hard rule.

For example when hiding something with a fade out or similar animation in applications I've worked on in the past I would trigger the DOM removal on the animation complete event. This is what I intend to do when I get around to halogen animations.

**Comment by garyb** [comment]
Makes sense with the hover stuff, just unfortunate it means introducing a fair bit of additional code on our side :wink:

Can you squash the commits please?

> Support for `aria-hidden` is not as high as support for reporting of dom removals and additions.

What do you mean by that?

Also, I'm a little confused as to the purpose of `aria-hidden` now. We seem to be misusing it a bit, from doing some reading, it seems that it's there to hide _visible_ elements from screenreaders (visual elements that are unhelpful to the reading experience), and using the `hidden` HTML5 attribute or `display: none` is the way to hide elements from everyone. ([See this](https://www.paciellogroup.com/blog/2016/01/the-state-of-hidden-content-support-in-2016/) for example)

**Comment by beckyconning** [comment]
Previously I found it unclear from inside the halogen component whether we are presenting the actions or not. I had to check both the Bootstrap docs, `SlamData.Render.CSS` to work this out.

I feel like these additions to state, query and eval express the difference between selecting something and just presenting its actions more clearly. 

This clarity gave me some insights:
* A selected file doesn't just present it's actions it also affects its ordering
* Selecting an item isn't the only way to present an file's actions
* Selecting an item doesn't seem to much value to the user over just presenting its actions. It seems to simply highlight the item and doesn't expose any features that couldn't be achieved though presenting its actions.

Regarding `aria-hidden` https://www.w3.org/TR/wai-aria-1.1/#aria-hidden

> It is recommended that authors key visibility of elements off this attribute, rather than change visibility and separately update this property. CSS 2 provides a way to select on attribute values ([CSS2]). The following CSS declaration makes content visible unless the aria-hidden attribute is true; scripts need only update the value of this attribute to change visibility: `[aria-hidden="true"] { visibility: hidden; }`

**Comment by beckyconning** [comment]
If `hidden` works as well as `aria-hidden` I'm more than happy for us to use that instead : ). :+1:

**Comment by garyb** [comment]
That's totally bizzare, it prevents an actually useful use-case of `aria-hidden`, and replicated functionality already supported by browsers and screen readers. (I'm not arguing with you, just saying the W3C recommendation seems wrong).

**Comment by beckyconning** [comment]
Squashed : ). Thanks @garyb I think this is a better decision for now.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
